### PR TITLE
Adapt to code changes in ij version 1.53d

### PR DESCRIPTION
**Pull request by imagejan**

### CODE REVIEW

**Comment by imagejan** [comment]
The Travis CI build for https://github.com/imagej/ij1-patcher/commit/0185003a0c4b34e6113d4c408f45ffbc494e1f27 passed, but only because I commented the code block that adds back the *Convert to 8-bit Grayscale* option:

https://github.com/imagej/ij1-patcher/blob/0185003a0c4b34e6113d4c408f45ffbc494e1f27/src/main/java/net/imagej/patcher/LegacyExtensions.java#L257-L281

The [`ij.plugin.FolderOpener`](https://github.com/imagej/ImageJA/blob/86434ec3e37c7796bc7a22c89a95eb804c0f4605/src/main/java/ij/plugin/FolderOpener.java) class underwent substantial changes, most importantly the nested class `FolderOpener$FolderOpenerDialog` was removed completely.

We need to add a test that actually uses `convertToGrayscale`, and make sure that it passes with recent as well as older versions of `ij.jar`.

---

Also, the changes with regard to `MacAdapter` likely need to be adapted to consider *both* `MacAdapter` (the default package, before 1.53d) and `ij.plugin.MacAdapter` (since 1.53d) for compatibility across ij versions.

**Comment by hinerm** [comment]
@imagejan  crud I'm sorry I didn't see this. I replicated it in https://github.com/imagej/ij1-patcher/commit/54c3af15afb16986c7937088a8b753ceba45327f

**Comment by imagejan** [comment]
@hinerm wrote:
> I replicated it in 54c3af1

except for the `MacAdapter => ij.plugin.MacAdapter`-related changes in `LegacyExtensions` and `LegacyInjector`.

**Comment by hinerm** [comment]
> except for the `MacAdapter => ij.plugin.MacAdapter`-related changes in `LegacyExtensions` and `LegacyInjector`.

😭 😭 you're right, I'm so sorry!

**Comment by hinerm** [comment]
@imagejan I rescued your patch: https://github.com/imagej/ij1-patcher/commit/0f3c057c9ff1bf9730e179d22a07607a538a41b9

**Pull request closed without merging**
