### PR TITLE
Adapt to code changes introduced in ImageJ 1.51s

### PR DESCRIPTION
**Pull request by stelfrich**
Due to refactoring patching has failed with recent versions of ImageJ1.

I have tested with 1.51s and 1.48. Both are working properly.

### CODE REVIEW

**Comment by ctrueden** [comment]
Thank you so much! 🥇

**Comment by imagejan** [comment]
The commit in this PR (https://github.com/imagej/ij1-patcher/commit/74a2412f01b53b9c0e30113e27b2c659e75ac8d1) is actually the first one that made [`FatJarTest`](https://github.com/imagej/ij1-patcher/blob/master/src/test/java/net/imagej/patcher/FatJarTest.java) fail (see the log of [this Travis build](https://travis-ci.org/imagej/ij1-patcher/builds/316402249#L527-L557)). 

This and the following builds were falsely reported as successful, but the test in fact failed. Only after adapting the build script, the [Travis builds](https://travis-ci.org/imagej/ij1-patcher/builds/377924147) started to actually fail the build upon test failure.

@ctrueden, @stelfrich do you have any clue why `FatJarTest` got broken?

**Comment by stelfrich** [comment]
Thanks for noticing, @imagejan!

I can build `master` without `FatJarTest` failing locally. This could also just be a coincidence and we haven't noticed in between those two commits, e.g. changes to the Travis build images or something like that. Do you observe the issue on a Windows machine as well, @imagejan?

**Comment by dscho** [comment]
Travis fails: https://travis-ci.org/imagej/ij1-patcher/builds/383341829?utm_source=github_status&utm_medium=notification. Might make sense to paste the surefire-reports upon failure...

**Comment by dscho** [comment]
> Travis fails

@stelfrich to make it abundandly clear what I meant: since Travis has no Windows boxes, this is not a Windows-specific failure, so you should be able to reproduce it either by tweaking your local setup or by analyzing in a PR (assuming that Travis builds are enabled for PRs).

**Comment by stelfrich** [comment]
> @stelfrich to make it abundandly clear what I meant: since Travis has no Windows boxes, this is not a Windows-specific failure

Thank you for this *very* constructive comment, @dscho.

Since there is a slight chance that it's an OS-specific issue, I was interested if the test was also failing on Windows. I know that the test passes on macOS, it fails on Linux, and I wanted to fill in the Windows gap.

**Comment by imagejan** [comment]
Sorry for the delayed reply, and thanks for following up, @stelfrich.

In fact, the current `master` branch builds fine on Windows. I had just noticed the build failures on Travis, and then went searching for the first time this test had failed in the Travis build history.

**Pull request merged**
